#!/bin/bash
if [[ `whoami` != 'root' ]]; then
echo "Please run as root"
exit 0	
fi

NGINXSTACKROOT="/opt/nginxstack-1.10.1-1"
PHPINI=${NGINXSTACKROOT}"/php/etc/php.ini"
PHPINIINTER="./php.ini.inter"

touch ${PHPINIINTER}

if [[ ! -f ${PHPINIINTER} ]]; then
	echo "Creating Intermediate File Failed!"
	exit 1
fi	

case $1 in
	on)
	cat ${PHPINI} | sed 's/xdebug.remote_enable=0/xdebug.remote_enable=1/' | sed 's/xdebug.profiler_enable=0/xdebug.remote_enable=1/' > ${PHPINIINTER}
    cp ${PHPINIINTER} ${PHPINI}
	sudo ${NGINXSTACKROOT}/ctlscript.sh restart php-fpm
	sleep 1	
	echo "Current Status"
    grep 'xdebug.remote_enable' ${PHPINI}
	;;

	off)
	cat ${PHPINI} | sed 's/xdebug.remote_enable=1/xdebug.remote_enable=0/' | sed 's/xdebug.profiler_enable=1/xdebug.remote_enable=0/' > ${PHPINIINTER}
	cp ${PHPINIINTER} ${PHPINI}
    sudo ${NGINXSTACKROOT}/ctlscript.sh restart php-fpm
	sleep 1
	echo "Current Status"
    grep 'xdebug.remote_enable' ${PHPINI}	
	;;
	
	*)
	echo "usage : sudo ./toggle_xdebug { on | off }"
	echo "Current Status"
    grep 'xdebug.remote_enable' ${PHPINI}
	;;

esac
